"""Broker-layer value objects shared between alpaca_client and risk_manager.

None of these models perform I/O. They are pure data containers validated at
construction time.
"""
from __future__ import annotations

import enum
import re
import secrets
from datetime import UTC, date, datetime, time, timedelta
from typing import Annotated
from zoneinfo import ZoneInfo

from pydantic import BaseModel, Field, field_validator, model_validator

# ── Enums ─────────────────────────────────────────────────────────────────────


class OrderSide(str, enum.Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, enum.Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP_LIMIT = "stop_limit"


class TimeInForce(str, enum.Enum):
    DAY = "day"
    GTC = "gtc"
    IOC = "ioc"


class RiskCheckCode(str, enum.Enum):
    # Happy path
    APPROVED = "APPROVED"
    # Checks 1–12 (ordered by cost, cheap first)
    BOT_PAUSED = "BOT_PAUSED"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    MARKET_CLOSED = "MARKET_CLOSED"
    SYMBOL_NOT_TRADEABLE = "SYMBOL_NOT_TRADEABLE"
    CLOCK_DRIFT = "CLOCK_DRIFT"
    DUPLICATE_ORDER = "DUPLICATE_ORDER"
    PRICE_OUT_OF_RANGE = "PRICE_OUT_OF_RANGE"
    INVALID_STOP_LOSS = "INVALID_STOP_LOSS"
    INSUFFICIENT_BUYING_POWER = "INSUFFICIENT_BUYING_POWER"
    POSITION_SIZE_EXCEEDED = "POSITION_SIZE_EXCEEDED"
    TOTAL_EXPOSURE_EXCEEDED = "TOTAL_EXPOSURE_EXCEEDED"
    MAX_POSITIONS_REACHED = "MAX_POSITIONS_REACHED"


# ── Validation helpers ────────────────────────────────────────────────────────

_CLIENT_ORDER_ID_RE = re.compile(r"^[A-Za-z0-9_-]{1,128}$")
# Any char NOT in the Alpaca-safe set is replaced with underscore.
# Example: BRK.B → BRK_B (dot is not in the allowed set).
_SYMBOL_SAFE_RE = re.compile(r"[^A-Za-z0-9_-]")


def make_client_order_id(strategy_version_id: int | None, symbol: str) -> str:
    """Generate an Alpaca-compatible client_order_id.

    Format: ``{strategy_id}-{SAFE_SYMBOL}-{timestamp_ms}-{nonce8hex}``
    Example: ``3-QQQ-1746800000123-ab12cd34``
             ``3-BRK_B-1746800000123-ab12cd34``  (dot sanitized to underscore)
    Max length: ~37 chars (well under Alpaca's 128-char limit).

    IMPORTANT — the symbol segment in the returned ID is an *opaque identifier*,
    NOT guaranteed to be the original ticker.  Sanitization is one-way:
    ``BRK.B`` and ``BRK_B`` both become ``BRK_B`` in the ID.  Never parse this
    field to recover the original symbol; use the ``symbol`` column in
    ``order_attempts`` as the authoritative source.

    Collision probability at 1000 req/s: nonce has 4_294_967_296 combinations.
    """
    ts_ms = int(datetime.now(UTC).timestamp() * 1000)
    nonce = secrets.token_hex(4)  # 8 hex chars = 2^32 combinations
    sid = strategy_version_id if strategy_version_id is not None else 0
    safe_symbol = _SYMBOL_SAFE_RE.sub("_", symbol.upper())
    oid = f"{sid}-{safe_symbol}-{ts_ms}-{nonce}"
    if len(oid) > 128:
        raise ValueError(f"client_order_id too long: {len(oid)} chars (should never happen)")
    return oid


# ── OrderIntent ───────────────────────────────────────────────────────────────


class OrderIntent(BaseModel):
    """A proposed order before risk validation and Alpaca submission.

    The engine creates this; the risk_manager validates it; alpaca_client
    submits it. The ``client_order_id`` must be pre-generated by the caller
    using ``make_client_order_id()`` and persisted to ``order_attempts``
    BEFORE calling alpaca_client.submit_order().
    """

    symbol: str
    side: OrderSide
    qty: float
    order_type: OrderType = OrderType.MARKET
    time_in_force: TimeInForce = TimeInForce.DAY
    limit_price: float | None = None
    stop_price: float | None = None
    client_order_id: str
    # True when closing or reducing an existing position. Exempt from
    # MAX_POSITIONS_REACHED and INVALID_STOP_LOSS checks.
    is_closing: bool = False
    # Human-readable description of the engine rule that fired this order.
    # Never generated by an LLM inside the trading loop.
    rule_trigger: str = ""
    strategy_version_id: int | None = None
    # Last known market price for the symbol (used in PRICE_OUT_OF_RANGE and
    # INSUFFICIENT_BUYING_POWER checks). Required for limit orders.
    estimated_price: float | None = None

    @field_validator("symbol")
    @classmethod
    def _validate_symbol(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("symbol must not be empty")
        if " " in v:
            raise ValueError("symbol must not contain spaces")
        return v.upper()

    @field_validator("qty")
    @classmethod
    def _validate_qty(cls, v: float) -> float:
        if v <= 0:
            raise ValueError(f"qty must be positive, got {v}")
        return v

    @field_validator("client_order_id")
    @classmethod
    def _validate_client_order_id(cls, v: str) -> str:
        if len(v) > 128:
            raise ValueError(f"client_order_id must be ≤ 128 chars, got {len(v)}")
        if not _CLIENT_ORDER_ID_RE.match(v):
            raise ValueError(
                f"client_order_id must match [A-Za-z0-9_-]{{1,128}}, got: {v!r}"
            )
        return v

    @model_validator(mode="after")
    def _limit_requires_price(self) -> OrderIntent:
        if self.order_type == OrderType.LIMIT and self.limit_price is None:
            raise ValueError("LIMIT orders require limit_price")
        return self

    @model_validator(mode="after")
    def _stop_limit_requires_both_prices(self) -> OrderIntent:
        if self.order_type == OrderType.STOP_LIMIT and (
            self.limit_price is None or self.stop_price is None
        ):
            raise ValueError("STOP_LIMIT orders require both limit_price and stop_price")
        return self


# ── ValidationResult ──────────────────────────────────────────────────────────


class ValidationResult(BaseModel):
    """Outcome of risk_manager.validate_order().

    Every validation — approved or rejected — is logged to ``alert_logs``
    for audit purposes. The ``code`` field identifies which check fired.
    Invariant: approved=True ↔ code=APPROVED.
    """

    approved: bool
    code: RiskCheckCode
    reason: str
    symbol: str
    estimated_order_value_usd: float | None = None
    checked_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @model_validator(mode="after")
    def _approved_code_consistent(self) -> ValidationResult:
        if self.approved and self.code != RiskCheckCode.APPROVED:
            raise ValueError(
                f"approved=True requires code=APPROVED, got code={self.code}"
            )
        if not self.approved and self.code == RiskCheckCode.APPROVED:
            raise ValueError("approved=False cannot have code=APPROVED")
        return self

    @classmethod
    def approve(
        cls,
        symbol: str,
        estimated_order_value_usd: float | None = None,
    ) -> ValidationResult:
        return cls(
            approved=True,
            code=RiskCheckCode.APPROVED,
            reason="All risk checks passed",
            symbol=symbol,
            estimated_order_value_usd=estimated_order_value_usd,
        )

    @classmethod
    def reject(
        cls,
        symbol: str,
        code: RiskCheckCode,
        reason: str,
        estimated_order_value_usd: float | None = None,
    ) -> ValidationResult:
        return cls(
            approved=False,
            code=code,
            reason=reason,
            symbol=symbol,
            estimated_order_value_usd=estimated_order_value_usd,
        )


# ── RiskOverrides ─────────────────────────────────────────────────────────────

_PCT_FIELD = Annotated[float | None, Field(default=None, gt=0.0, le=100.0)]
_STOP_LOSS_FIELD = Annotated[float | None, Field(default=None, gt=0.0, le=50.0)]
_POS_INT_FIELD = Annotated[int | None, Field(default=None, gt=0, le=50)]


class RiskOverrides(BaseModel):
    """Active overrides set via /setlimit Telegram command.

    Overrides are always *more restrictive* than the strategy defaults —
    the risk_manager takes ``min(strategy_value, override_value)`` for each
    parameter. Attempting to set a less-restrictive override is logged as
    a warning and the strategy value is kept.

    Built at runtime from the latest active ``RiskOverride`` DB rows
    (one per param_name, most recent wins).

    Field bounds are sanity checks enforced at input time, not Alpaca limits:
    ``max_concurrent_positions ≤ 50`` is arbitrary and can be raised here if
    a strategy genuinely needs more simultaneous open positions.
    """

    max_position_pct: _PCT_FIELD = None
    max_total_exposure_pct: _PCT_FIELD = None
    stop_loss_pct: _STOP_LOSS_FIELD = None
    max_concurrent_positions: _POS_INT_FIELD = None


# ── Broker return value objects ───────────────────────────────────────────────


class AssetInfo(BaseModel):
    """Alpaca asset metadata cached by AssetCache."""

    symbol: str
    name: str
    tradeable: bool
    fractionable: bool
    shortable: bool
    easy_to_borrow: bool
    status: str  # "active" | "inactive"


class AccountSnapshot(BaseModel):
    """Point-in-time account state fetched from Alpaca."""

    buying_power: float
    cash: float
    portfolio_value: float
    pattern_day_trader: bool
    trading_blocked: bool
    account_blocked: bool
    snapshot_at: datetime  # UTC, timestamp of the API call


class PositionSnapshot(BaseModel):
    """Open position as reported by Alpaca."""

    symbol: str
    qty: float              # positive = long, negative = short
    side: str               # "long" | "short"
    market_value: float
    avg_entry_price: float
    unrealized_pl: float
    unrealized_plpc: float  # fraction: 0.05 = 5 %
    current_price: float


class OrderSubmitResult(BaseModel):
    """Result returned by AlpacaClient.submit_order()."""

    alpaca_order_id: str    # "dry-{client_order_id}" when simulated=True
    client_order_id: str
    status: str             # Alpaca order status at submission time ("new", "pending_new", …)
    submitted_at: datetime
    simulated: bool = False  # True when settings.dry_run=True; never rely on the ID prefix


class BarData(BaseModel):
    """Single OHLCV bar returned by AlpacaClient.get_bars()."""

    symbol: str
    timestamp: datetime     # UTC, start of bar
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float | None = None


class ClockSnapshot(BaseModel):
    """Alpaca server clock snapshot used for drift detection.

    ``drift_seconds = local_timestamp - alpaca_timestamp``
    Positive value means the local clock is ahead of Alpaca's.
    Negative value means the local clock is behind.
    """

    alpaca_timestamp: datetime
    local_timestamp: datetime
    drift_seconds: float    # local - alpaca (positive = local ahead)
    is_open: bool
    next_open: datetime | None = None
    next_close: datetime | None = None


class OrderStatusResult(BaseModel):
    """Current state of an order fetched after submission.

    Returned by AlpacaClient.get_order() and consumed by the engine and
    stream callbacks to reconcile fills.  Distinct from OrderSubmitResult,
    which is the snapshot captured at submission time only.
    """

    alpaca_order_id: str
    client_order_id: str
    status: str             # "new" | "filled" | "partially_filled" | "canceled" | "rejected" | …
    submitted_at: datetime
    filled_at: datetime | None = None
    canceled_at: datetime | None = None
    filled_qty: float = 0.0
    filled_avg_price: float | None = None
    side: OrderSide
    symbol: str
    qty: float


class MarketCalendarDay(BaseModel):
    """Single trading-day entry from the Alpaca market calendar.

    Times are stored in UTC for unambiguous scheduling.
    Use ``open_et`` / ``close_et`` properties for ET wall-clock display.
    The mapper in AlpacaClient localizes the naive ET datetimes returned by
    the SDK before constructing this model.
    """

    date: date
    session_open_utc: datetime
    session_close_utc: datetime

    @field_validator("session_open_utc", "session_close_utc")
    @classmethod
    def _must_be_utc(cls, v: datetime) -> datetime:
        if v.tzinfo is None:
            raise ValueError("session times must be timezone-aware UTC")
        if v.utcoffset() != timedelta(0):
            raise ValueError(f"session times must be in UTC, got offset {v.utcoffset()}")
        return v

    @property
    def open_et(self) -> time:
        return self.session_open_utc.astimezone(ZoneInfo("America/New_York")).time()

    @property
    def close_et(self) -> time:
        return self.session_close_utc.astimezone(ZoneInfo("America/New_York")).time()


# ── Stream event value objects ────────────────────────────────────────────────

# Trade event strings observed from the Alpaca paper API (verified 2026-05-10).
# Not exhaustive — the SDK may emit additional values in future releases.
# Use this set to distinguish known events from unexpected ones; do not reject
# unknown events at parse time (stream_manager passes event strings through).
KNOWN_TRADE_EVENTS: frozenset[str] = frozenset({
    "fill",
    "partial_fill",
    "canceled",
    "rejected",
    "new",
    "accepted",
    "pending_new",
    "pending_cancel",
    "expired",
    "replaced",
    "done_for_day",
    "stopped",
    "suspended",
    "restated",
})


class TradeUpdateEvent(BaseModel):
    """Trade lifecycle event received from Alpaca's TradingStream."""

    event: str
    order: OrderStatusResult
    timestamp: datetime  # UTC, tz-aware

    @field_validator("timestamp")
    @classmethod
    def _must_be_tz_aware(cls, v: datetime) -> datetime:
        if v.tzinfo is None:
            raise ValueError("timestamp must be timezone-aware")
        return v


class BarEvent(BaseModel):
    """Real-time OHLCV bar received from Alpaca's StockDataStream."""

    bar: BarData
    received_at: datetime  # UTC, wall-clock time the event was processed

    @field_validator("received_at")
    @classmethod
    def _must_be_tz_aware(cls, v: datetime) -> datetime:
        if v.tzinfo is None:
            raise ValueError("received_at must be timezone-aware")
        return v
